config/routes.rb
Rails.application.routes.draw do
  resources :rolls, only: [:new, :create]
  root 'rolls#new'
  get 'about' => 'static_pages#about'
end

app/models/roll.rb
class Roll < ActiveRecord::Base
  validates_numericality_of :sides, in => 3..30 
  validates :number, presence: true, inclusion: { in 1..30 }
end

app/models/rolls.rb
class Roll < ActiveRecord::Base
  validates_numericality_of :sides, in => 3..30 
  validates :number, presence: true, inclusion: { in 1..30 }

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rolls_controller.rb
class RollsController < ApplicationController

	def new
	end

	def create
		@sides = params[:sides].to_i
		@number = params[:number].to_i
		@result = roll_dice(@sides, @number)
	end

	def roll_dice(sides, number)
		#if valid?
			(1..number).map do
				roll_die(sides)
			end
		#else
			#flash[:danger] = "Die must have at least 3 sides and no more than 30. You may only roll up to 30 dice."
		#end
	end

	def roll_die(sides)
		rand(1..sides)
	end

	#def valid_die
		#@sides = params[:sides].to_i
		#@sides = {3..31}
	#end

	#def valid?
		#@sides = params[:sides].to_i
		#@sides == (3..30)
	#end		
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roll_helper.rb
module RollHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li><%= link_to "Home", root_path, class: "btn btn-lg btn-primary" %></li>
    <li><%= link_to "About", about_path, class: "btn btn-lg btn-primary" %></li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("dice.jpg", class: "icon") %>
  <%= image_tag("dice.jpg", class: "icon2") %>
  <p> Welcome to the Dice Rolling Madhouse. </p>
  <p> Come on in and roll some dice! </p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiceRoller</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <%= render 'layouts/header' %>

    <main>
      <%= yield %>
    </main>

      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/rolls/_rolls.html.erb
<%= label_tag :sides %>
<%= number_field_tag :sides, @sides, min: 4, max: 50 %>

<%= label_tag :number %>
<%= number_field_tag :number, @number, min: 1, max: 20 %>

app/views/rolls/create.html.erb
<div class="table">
	<h1>
		<p>
			You rolled <%= @number %>, <%= @sides %> sided dice. Here are your results...
		</p>
	</h1>

	<div class="results">
		<ul>
			<% @result.each do |result| %>
				<li class='<%= "crit" if result==@sides %>'>
					<%= result %>
				</li>
			<% end %>
		</ul>
	</div>

	<div class="form2">
		<%= form_tag(rolls_path) do %>
			<%= render 'rolls/rolls' %>

			<%= submit_tag "Roll again" %>
		<% end %>
	</div>
</div>

app/views/rolls/new.html.erb
<div class="form">
  <%= form_tag(rolls_path) do %>
	 <%= render 'rolls/rolls' %>

	 <%= submit_tag "Roll 'em up" %>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<div class="block-text">
  <h1>
    About
  </h1>
  <p>
    Inspiration for this app came whilst playing Twilight Imperium. If you haven't heard of this game it is an epic board game of strategy, politics, trade and war. The game is set in a period of unrest where the Imperial throne has been left vacant and every player (representing a different civilization) has a claim to it. Each civilization has unique strengths and weaknesses. Some are blood-thirsty and will battle their way to the throne. Others are studious and make up for their lack of strength with technology. Playing with six different civilizations it is inevitable that the struggle for power will build up to a large war and war means dice! On our latest play through we had several bloody wars and we needed more dice...
  </p>
  <p>
    Wouldn't it be nice to have the exact number and kind of dice you need?
  </p>
  <p>
    Well step on up, this app is for you.
  </p>
</div>